import json
import os

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# 🤟 SANA A-PSL: Google Colab Video Landmark Extraction & Augmentation Pipeline\n",
            "**Goal:** Ingest raw video recordings directly from your specified Google Drive path (`Test Data/{label}/[videos]`), extract **208-dimensional MediaPipe landmark sequences**, apply **6× Data Augmentation**, and save the processed `.npy` dataset and ZIP file directly to Google Drive.\n",
            "\n",
            "### 📁 Expected Folder Hierarchy:\n",
            "```\n",
            "<YOUR_SPECIFIED_PATH>/\n",
            "├── headache/\n",
            "│   ├── video_01.mp4\n",
            "│   └── video_02.mp4\n",
            "├── stomach_pain/\n",
            "│   ├── video_01.mp4\n",
            "│   └── video_02.mp4\n",
            "└── fever/\n",
            "    ├── video_01.mp4\n",
            "    └── video_02.mp4\n",
            "```\n",
            "\n",
            "### 📐 208-Dimension Feature Layout per Frame:\n",
            "- `[0:66]`   : 33 Pose landmarks $(X, Y)$\n",
            "- `[66:108]` : 21 Left Hand landmarks $(X, Y)$\n",
            "- `[108:150]`: 21 Right Hand landmarks $(X, Y)$\n",
            "- `[150:208]`: 29 Expression Face landmarks / Neutral 0s $(X, Y)$"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ── Cell 1: Mount Google Drive & Install Dependencies ────────────────────────\n",
            "from google.colab import drive\n",
            "drive.mount('/content/drive')\n",
            "\n",
            "!pip install -q mediapipe opencv-python numpy matplotlib tqdm pandas\n",
            "\n",
            "import os\n",
            "import sys\n",
            "import glob\n",
            "import json\n",
            "import math\n",
            "import random\n",
            "import shutil\n",
            "from pathlib import Path\n",
            "\n",
            "import cv2\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import matplotlib.pyplot as plt\n",
            "from tqdm.auto import tqdm\n",
            "\n",
            "import mediapipe as mp\n",
            "\n",
            "print(\"\\n\" + \"=\" * 60)\n",
            "print(\"✅ Google Drive Mounted & Dependencies Installed Successfully!\")\n",
            "print(f\"OpenCV Version:    {cv2.__version__}\")\n",
            "print(f\"MediaPipe Version: {mp.__version__}\")\n",
            "print(\"=\" * 60)"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ── Cell 2: Specify Your Dataset Path & Configuration ────────────────────────\n",
            "# 👇 SPECIFY YOUR EXACT GOOGLE DRIVE DATASET PATH HERE:\n",
            "DATASET_PATH = \"/content/drive/MyDrive/Test Data\"\n",
            "\n",
            "CONFIG = {\n",
            "    # Paths\n",
            "    \"RAW_VIDEOS_DIR\":       DATASET_PATH,                         # Folder with {label} subfolders\n",
            "    \"LOCAL_OUTPUT_DIR\":     \"/content/processed_psl_dataset\",     # Fast local processing directory\n",
            "    \"GDRIVE_BACKUP_DIR\":    \"/content/drive/MyDrive/SANA_PSL_Processed_Dataset\", # Backup directory in GDrive\n",
            "    \"OUTPUT_ZIP_NAME\":      \"SANA_PSL_Keypoints_Dataset.zip\",\n",
            "    \n",
            "    # Landmark Extraction Parameters\n",
            "    \"INPUT_DIM\":            208,                                  # 66 Pose + 42 LH + 42 RH + 58 Face\n",
            "    \"TARGET_FRAMES\":        60,                                   # Resample all sequences to 60 frames (SANA Conv1D standard)\n",
            "    \"MIN_DETECTION_CONF\":   0.5,\n",
            "    \"MIN_TRACKING_CONF\":    0.5,\n",
            "    \"SMOOTHING_ALPHA\":      0.75,                                 # Temporal coordinate smoothing\n",
            "    \"MIRROR_CORRECTION\":    True,                                 # Set True if recorded with front selfie camera\n",
            "    \n",
            "    # 6x Data Augmentation\n",
            "    \"ENABLE_AUGMENTATION\":  True,\n",
            "    \"AUGMENTATION_FACTOR\":  5,                                    # 1 Original + 5 Augmented = 6x Expansion\n",
            "    \"SCALE_RANGE\":          (0.85, 1.15),                         # Spatial distance variation\n",
            "    \"SHIFT_RANGE\":          (-0.06, 0.06),                        # Spatial centering translation\n",
            "    \"SPEED_RANGE\":          (0.85, 1.15),                         # Temporal speed variation\n",
            "    \"JITTER_SIGMA\":         0.003,                                # Coordinate noise\n",
            "}\n",
            "\n",
            "os.makedirs(CONFIG[\"LOCAL_OUTPUT_DIR\"], exist_ok=True)\n",
            "os.makedirs(CONFIG[\"GDRIVE_BACKUP_DIR\"], exist_ok=True)\n",
            "\n",
            "print(\"=\" * 60)\n",
            "print(f\"📂 Specified Dataset Path:    {CONFIG['RAW_VIDEOS_DIR']}\")\n",
            "print(f\"💾 Permanent GDrive Backup:   {CONFIG['GDRIVE_BACKUP_DIR']}\")\n",
            "print(f\"⚡ Local Processing Output:    {CONFIG['LOCAL_OUTPUT_DIR']}\")\n",
            "print(\"=\" * 60)\n",
            "\n",
            "if not os.path.exists(CONFIG[\"RAW_VIDEOS_DIR\"]):\n",
            "    print(f\"⚠️ Error: Directory '{CONFIG['RAW_VIDEOS_DIR']}' does not exist.\")\n",
            "    print(\"👉 Please verify your DATASET_PATH string at the top of this cell!\")\n",
            "else:\n",
            "    labels = [d for d in os.listdir(CONFIG[\"RAW_VIDEOS_DIR\"]) if os.path.isdir(os.path.join(CONFIG[\"RAW_VIDEOS_DIR\"], d))]\n",
            "    print(f\"✅ Directory verified! Found {len(labels)} label subfolders:\")\n",
            "    print(labels)"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ── Cell 3: MediaPipe Holistic 208-Dimension Landmark Extractor ─────────────\n",
            "class MediaPipeVideoExtractor:\n",
            "    def __init__(self, min_detection_conf=0.5, min_tracking_conf=0.5, mirror_fix=True, alpha=0.75):\n",
            "        self.mp_holistic = mp.solutions.holistic\n",
            "        self.holistic = self.mp_holistic.Holistic(\n",
            "            static_image_mode=False,\n",
            "            model_complexity=2,\n",
            "            enable_segmentation=False,\n",
            "            refine_face_landmarks=False,\n",
            "            min_detection_confidence=min_detection_conf,\n",
            "            min_tracking_confidence=min_tracking_conf\n",
            "        )\n",
            "        self.mirror_fix = mirror_fix\n",
            "        self.alpha = alpha\n",
            "        self.prev_landmarks = None\n",
            "        \n",
            "    def reset_tracker(self):\n",
            "        self.prev_landmarks = None\n",
            "        \n",
            "    def extract_frame(self, frame_bgr):\n",
            "        \"\"\"\n",
            "        Extracts exactly 208 normalized (x, y) coordinates from a single frame.\n",
            "        Returns: np.ndarray shape (208,)\n",
            "        \"\"\"\n",
            "        frame_rgb = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)\n",
            "        results = self.holistic.process(frame_rgb)\n",
            "        \n",
            "        # 1. Pose Landmarks (33 points -> 66 floats: x, y)\n",
            "        pose_coords = [0.0] * 66\n",
            "        if results.pose_landmarks:\n",
            "            for i, lm in enumerate(results.pose_landmarks.landmark):\n",
            "                pose_coords[i*2] = float(lm.x)\n",
            "                pose_coords[i*2 + 1] = float(lm.y)\n",
            "                \n",
            "        # 2. Left Hand Landmarks (21 points -> 42 floats: x, y)\n",
            "        lh_coords = [0.0] * 42\n",
            "        if results.left_hand_landmarks:\n",
            "            for i, lm in enumerate(results.left_hand_landmarks.landmark):\n",
            "                lh_coords[i*2] = float(lm.x)\n",
            "                lh_coords[i*2 + 1] = float(lm.y)\n",
            "                \n",
            "        # 3. Right Hand Landmarks (21 points -> 42 floats: x, y)\n",
            "        rh_coords = [0.0] * 42\n",
            "        if results.right_hand_landmarks:\n",
            "            for i, lm in enumerate(results.right_hand_landmarks.landmark):\n",
            "                rh_coords[i*2] = float(lm.x)\n",
            "                rh_coords[i*2 + 1] = float(lm.y)\n",
            "                \n",
            "        # Handle Selfie Mirror Inversion if enabled\n",
            "        if self.mirror_fix:\n",
            "            lh_coords, rh_coords = rh_coords, lh_coords\n",
            "            \n",
            "        # 4. Face Landmarks (58 floats - neutral zeros for SANA standard)\n",
            "        face_coords = [0.0] * 58\n",
            "        \n",
            "        # Concatenate into 208 floats\n",
            "        current_frame_208 = np.array(pose_coords + lh_coords + rh_coords + face_coords, dtype=np.float32)\n",
            "        \n",
            "        # Coordinate smoothing across consecutive frames\n",
            "        if self.prev_landmarks is None:\n",
            "            self.prev_landmarks = current_frame_208\n",
            "        else:\n",
            "            active_mask = (current_frame_208 != 0.0).astype(np.float32)\n",
            "            smoothed = active_mask * (self.alpha * current_frame_208 + (1 - self.alpha) * self.prev_landmarks) + (1 - active_mask) * current_frame_208\n",
            "            self.prev_landmarks = smoothed\n",
            "            current_frame_208 = smoothed\n",
            "            \n",
            "        return current_frame_208\n",
            "\n",
            "    def extract_from_video(self, video_path):\n",
            "        \"\"\"\n",
            "        Ingests a video file and extracts the full temporal sequence of landmarks.\n",
            "        Returns: np.ndarray of shape (T, 208), fps, total_frames\n",
            "        \"\"\"\n",
            "        cap = cv2.VideoCapture(video_path)\n",
            "        if not cap.isOpened():\n",
            "            print(f\"⚠️ Error: Could not open video {video_path}\")\n",
            "            return None, 0, 0\n",
            "        \n",
            "        fps = cap.get(cv2.CAP_PROP_FPS)\n",
            "        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))\n",
            "        \n",
            "        self.reset_tracker()\n",
            "        sequence = []\n",
            "        \n",
            "        while cap.isOpened():\n",
            "            ret, frame = cap.read()\n",
            "            if not ret:\n",
            "                break\n",
            "            landmarks_208 = self.extract_frame(frame)\n",
            "            sequence.append(landmarks_208)\n",
            "            \n",
            "        cap.release()\n",
            "        \n",
            "        if len(sequence) == 0:\n",
            "            return None, fps, 0\n",
            "            \n",
            "        return np.array(sequence, dtype=np.float32), fps, len(sequence)\n",
            "\n",
            "    def close(self):\n",
            "        self.holistic.close()\n",
            "\n",
            "print(\"✅ MediaPipe Holistic Extractor Class Initialized.\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ── Cell 4: Temporal Spline Resampling (60 Frames) ───────────────────────────\n",
            "def resample_sequence(sequence, target_frames=60):\n",
            "    \"\"\"\n",
            "    Resamples an arbitrary length landmark sequence (T, 208) to exactly target_frames (e.g. 60)\n",
            "    using linear/spline temporal interpolation.\n",
            "    \"\"\"\n",
            "    T = sequence.shape[0]\n",
            "    if T == target_frames:\n",
            "        return sequence\n",
            "    \n",
            "    orig_times = np.linspace(0, 1, T)\n",
            "    target_times = np.linspace(0, 1, target_frames)\n",
            "    \n",
            "    resampled = np.zeros((target_frames, sequence.shape[1]), dtype=np.float32)\n",
            "    for dim in range(sequence.shape[1]):\n",
            "        resampled[:, dim] = np.interp(target_times, orig_times, sequence[:, dim])\n",
            "        \n",
            "    return resampled\n",
            "\n",
            "print(\"✅ 60-Frame Temporal Resampling Function ready.\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ── Cell 5: 6× Data Synthesis & Augmentation Engine ──────────────────────────\n",
            "class LandmarkAugmentor:\n",
            "    def __init__(self, scale_range=(0.85, 1.15), shift_range=(-0.05, 0.05), speed_range=(0.85, 1.15), jitter_sigma=0.003):\n",
            "        self.scale_range = scale_range\n",
            "        self.shift_range = shift_range\n",
            "        self.speed_range = speed_range\n",
            "        self.jitter_sigma = jitter_sigma\n",
            "        \n",
            "    def augment(self, sequence_60):\n",
            "        \"\"\"\n",
            "        Applies random spatial scaling, 2D translation, temporal speed warping, and jitter.\n",
            "        Input:  (60, 208)\n",
            "        Output: (60, 208) newly synthesized variation\n",
            "        \"\"\"\n",
            "        aug_seq = sequence_60.copy()\n",
            "        T = aug_seq.shape[0]\n",
            "        \n",
            "        # 1. Temporal Speed Warping\n",
            "        speed_factor = random.uniform(*self.speed_range)\n",
            "        warped_len = max(10, int(T * speed_factor))\n",
            "        orig_t = np.linspace(0, 1, T)\n",
            "        warp_t = np.linspace(0, 1, warped_len)\n",
            "        warped = np.zeros((warped_len, 208), dtype=np.float32)\n",
            "        for d in range(208):\n",
            "            warped[:, d] = np.interp(warp_t, orig_t, aug_seq[:, d])\n",
            "        aug_seq = resample_sequence(warped, target_frames=T)\n",
            "        \n",
            "        # 2. Spatial Scaling\n",
            "        scale = random.uniform(*self.scale_range)\n",
            "        \n",
            "        # 3. Spatial Translation\n",
            "        shift_x = random.uniform(*self.shift_range)\n",
            "        shift_y = random.uniform(*self.shift_range)\n",
            "        \n",
            "        # 4. Coordinate Jitter\n",
            "        jitter = np.random.normal(0, self.jitter_sigma, size=aug_seq.shape).astype(np.float32)\n",
            "        \n",
            "        for t in range(T):\n",
            "            for i in range(0, 150, 2): # Apply to Pose, Left Hand, Right Hand\n",
            "                if aug_seq[t, i] != 0.0 or aug_seq[t, i+1] != 0.0:\n",
            "                    x_centered = (aug_seq[t, i] - 0.5) * scale + 0.5 + shift_x + jitter[t, i]\n",
            "                    y_centered = (aug_seq[t, i+1] - 0.5) * scale + 0.5 + shift_y + jitter[t, i+1]\n",
            "                    aug_seq[t, i] = np.clip(x_centered, 0.0, 1.0)\n",
            "                    aug_seq[t, i+1] = np.clip(y_centered, 0.0, 1.0)\n",
            "                    \n",
            "        return aug_seq\n",
            "\n",
            "augmentor = LandmarkAugmentor(\n",
            "    scale_range=CONFIG[\"SCALE_RANGE\"],\n",
            "    shift_range=CONFIG[\"SHIFT_RANGE\"],\n",
            "    speed_range=CONFIG[\"SPEED_RANGE\"],\n",
            "    jitter_sigma=CONFIG[\"JITTER_SIGMA\"]\n",
            ")\n",
            "print(\"✅ 6x Data Augmentation Engine initialized.\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ── Cell 6: Scan Subfolders for Labels & Extract Keypoints ────────────────────\n",
            "def scan_label_subfolders(root_dir):\n",
            "    \"\"\"\n",
            "    Scans the specified root_dir for label subfolders and video files.\n",
            "    Expected structure: root_dir/{label}/[videos]\n",
            "    \"\"\"\n",
            "    extensions = ('*.mp4', '*.avi', '*.mov', '*.webm', '*.mkv', '*.MP4', '*.AVI', '*.MOV')\n",
            "    samples = []\n",
            "    \n",
            "    if not os.path.exists(root_dir):\n",
            "        print(f\"⚠️ Error: Path '{root_dir}' does not exist.\")\n",
            "        return []\n",
            "        \n",
            "    subfolders = [d for d in sorted(os.listdir(root_dir)) if os.path.isdir(os.path.join(root_dir, d))]\n",
            "    \n",
            "    for label_name in subfolders:\n",
            "        label_dir = os.path.join(root_dir, label_name)\n",
            "        label_videos = []\n",
            "        for ext in extensions:\n",
            "            label_videos.extend(glob.glob(os.path.join(label_dir, ext)))\n",
            "            \n",
            "        for vpath in sorted(set(label_videos)):\n",
            "            samples.append({\n",
            "                \"video_path\": vpath,\n",
            "                \"label\": label_name,\n",
            "                \"file_name\": os.path.basename(vpath)\n",
            "            })\n",
            "            \n",
            "    return samples\n",
            "\n",
            "samples = scan_label_subfolders(CONFIG[\"RAW_VIDEOS_DIR\"])\n",
            "labels_found = sorted(list(set([s['label'] for s in samples])))\n",
            "\n",
            "print(f\"🔍 Scanned: '{CONFIG['RAW_VIDEOS_DIR']}'\")\n",
            "print(f\"📊 Found {len(samples)} total videos across {len(labels_found)} classes:\")\n",
            "for lbl in labels_found:\n",
            "    count = len([s for s in samples if s['label'] == lbl])\n",
            "    print(f\"   • {lbl:<25}: {count} videos\")\n",
            "\n",
            "if len(samples) == 0:\n",
            "    print(\"\\n⚠️ No video files found. Please check your DATASET_PATH in Cell 2!\")\n",
            "else:\n",
            "    extractor = MediaPipeVideoExtractor(\n",
            "        min_detection_conf=CONFIG[\"MIN_DETECTION_CONF\"],\n",
            "        min_tracking_conf=CONFIG[\"MIN_TRACKING_CONF\"],\n",
            "        mirror_fix=CONFIG[\"MIRROR_CORRECTION\"],\n",
            "        alpha=CONFIG[\"SMOOTHING_ALPHA\"]\n",
            "    )\n",
            "    \n",
            "    dataset_records = []\n",
            "    print(\"\\n🚀 Starting Landmark Extraction & 6x Augmentation Pipeline...\")\n",
            "    \n",
            "    for item in tqdm(samples, desc=\"Extracting Keypoints\"):\n",
            "        vpath = item[\"video_path\"]\n",
            "        label = item[\"label\"]\n",
            "        fname = Path(item[\"file_name\"]).stem\n",
            "        \n",
            "        raw_seq, fps, frame_count = extractor.extract_from_video(vpath)\n",
            "        if raw_seq is None or frame_count < 5:\n",
            "            print(f\"⚠️ Skipping {vpath} (insufficient frames: {frame_count})\")\n",
            "            continue\n",
            "            \n",
            "        # Resample to 60 frames\n",
            "        resampled_60 = resample_sequence(raw_seq, target_frames=CONFIG[\"TARGET_FRAMES\"])\n",
            "        \n",
            "        # Output directory for this class\n",
            "        class_dir = os.path.join(CONFIG[\"LOCAL_OUTPUT_DIR\"], label)\n",
            "        os.makedirs(class_dir, exist_ok=True)\n",
            "        \n",
            "        # 1. Save Clean Original Keypoints\n",
            "        orig_out_path = os.path.join(class_dir, f\"{fname}_orig.npy\")\n",
            "        np.save(orig_out_path, resampled_60)\n",
            "        dataset_records.append({\n",
            "            \"npy_path\": orig_out_path,\n",
            "            \"label\": label,\n",
            "            \"type\": \"original\",\n",
            "            \"raw_frames\": frame_count,\n",
            "            \"resampled_frames\": CONFIG[\"TARGET_FRAMES\"],\n",
            "            \"fps\": fps\n",
            "        })\n",
            "        \n",
            "        # 2. Synthesize 5 Augmented Variations (6x Total Expansion)\n",
            "        if CONFIG[\"ENABLE_AUGMENTATION\"]:\n",
            "            for aug_idx in range(1, CONFIG[\"AUGMENTATION_FACTOR\"] + 1):\n",
            "                aug_seq = augmentor.augment(resampled_60)\n",
            "                aug_out_path = os.path.join(class_dir, f\"{fname}_aug_{aug_idx:02d}.npy\")\n",
            "                np.save(aug_out_path, aug_seq)\n",
            "                dataset_records.append({\n",
            "                    \"npy_path\": aug_out_path,\n",
            "                    \"label\": label,\n",
            "                    \"type\": f\"augmented_{aug_idx}\",\n",
            "                    \"raw_frames\": frame_count,\n",
            "                    \"resampled_frames\": CONFIG[\"TARGET_FRAMES\"],\n",
            "                    \"fps\": fps\n",
            "                })\n",
            "                \n",
            "    extractor.close()\n",
            "    print(f\"\\n🎉 Extraction Complete! Generated {len(dataset_records)} processed .npy arrays.\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ── Cell 7: Metadata & Bilingual Translation Mapping ─────────────────────────\n",
            "# Standard Bilingual Medical Translation Mapping (English + Native Urdu)\n",
            "BILINGUAL_DICTIONARY = {\n",
            "    \"headache\":         (\"I have a severe headache\", \"میرے سر میں شدید درد ہے\"),\n",
            "    \"stomach_pain\":     (\"My stomach hurts\", \"میرے پیٹ میں درد ہے\"),\n",
            "    \"chest_pain\":       (\"I have chest pain\", \"میرے سینے میں درد ہے\"),\n",
            "    \"fever\":            (\"I have a high fever\", \"مجھے تیز بخار ہے\"),\n",
            "    \"cough\":            (\"I have a cough\", \"مجھے کھانسی ہے\"),\n",
            "    \"dizziness\":        (\"I feel dizzy\", \"مجھے چکر آ رہے ہیں\"),\n",
            "    \"nausea\":           (\"I feel nauseous\", \"مجھے متلی ہو رہی ہے\"),\n",
            "    \"allergy\":          (\"I have an allergy\", \"مجھے الرجی ہے\"),\n",
            "    \"diabetes\":         (\"I have diabetes\", \"مجھے شوگر ہے\"),\n",
            "    \"blood_pressure\":   (\"My blood pressure is high\", \"میرا بلڈ پریشر زیادہ ہے\"),\n",
            "    \"breathless\":       (\"I cannot breathe properly\", \"مجھے سانس لینے میں دشواری ہو رہی ہے\"),\n",
            "    \"bleeding\":         (\"There is bleeding\", \"خون بہہ رہا ہے\"),\n",
            "    \"broken_bone\":      (\"My bone is fractured\", \"میری ہڈی ٹوٹ گئی ہے\"),\n",
            "    \"burn\":             (\"I have a burn injury\", \"میرا ہاتھ جل گیا ہے\"),\n",
            "    \"medicine\":         (\"I need my medicine\", \"مجھے میری دوائی چاہیے\"),\n",
            "    \"water\":            (\"Please give me water\", \"براہ کرم مجھے پانی دیں\"),\n",
            "    \"doctor\":           (\"I need to see a doctor\", \"مجھے ڈاکٹر سے ملنا ہے\"),\n",
            "    \"help\":             (\"Please help me\", \"براہ کرم میری مدد کریں\"),\n",
            "    \"emergency\":        (\"This is an emergency\", \"یہ ایمرجنسی ہے\"),\n",
            "    \"pain_scale_high\":  (\"The pain is very intense (10/10)\", \"درد بہت شدید ہے\"),\n",
            "}\n",
            "\n",
            "if 'dataset_records' in locals() and len(dataset_records) > 0:\n",
            "    df = pd.DataFrame(dataset_records)\n",
            "    \n",
            "    df[\"english_translation\"] = df[\"label\"].apply(\n",
            "        lambda c: BILINGUAL_DICTIONARY.get(c.lower(), (c.replace('_', ' ').title(), \"\"))[0]\n",
            "    )\n",
            "    df[\"urdu_translation\"] = df[\"label\"].apply(\n",
            "        lambda c: BILINGUAL_DICTIONARY.get(c.lower(), (\"\", \"\"))[1]\n",
            "    )\n",
            "    \n",
            "    local_csv_path = os.path.join(CONFIG[\"LOCAL_OUTPUT_DIR\"], \"dataset_metadata.csv\")\n",
            "    df.to_csv(local_csv_path, index=False)\n",
            "    print(f\"📄 Metadata CSV generated: {local_csv_path}\")\n",
            "    display(df.head(10))\n",
            "else:\n",
            "    print(\"ℹ️ Metadata will be generated once videos are processed in Cell 6.\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ── Cell 8: Visual Skeleton Verification Strip ───────────────────────────────\n",
            "def plot_extracted_skeleton(npy_path, frame_indices=[0, 15, 30, 45, 59]):\n",
            "    \"\"\"\n",
            "    Plots 2D skeletal pose and hands across multiple frames to verify tracking.\n",
            "    \"\"\"\n",
            "    data = np.load(npy_path) # Shape: (60, 208)\n",
            "    T = data.shape[0]\n",
            "    \n",
            "    fig, axes = plt.subplots(1, len(frame_indices), figsize=(18, 4))\n",
            "    fig.suptitle(f\"SANA Skeleton Tracking: {os.path.basename(npy_path)}\", fontsize=14, y=1.05)\n",
            "    \n",
            "    for idx, f_idx in enumerate(frame_indices):\n",
            "        f_idx = min(f_idx, T - 1)\n",
            "        frame_data = data[f_idx]\n",
            "        \n",
            "        pose_xy = frame_data[0:66].reshape(-1, 2)\n",
            "        lh_xy   = frame_data[66:108].reshape(-1, 2)\n",
            "        rh_xy   = frame_data[108:150].reshape(-1, 2)\n",
            "        \n",
            "        ax = axes[idx]\n",
            "        ax.set_title(f\"Frame {f_idx}/{T}\")\n",
            "        ax.set_xlim(0, 1)\n",
            "        ax.set_ylim(1, 0) # Invert Y for standard image view\n",
            "        ax.set_aspect('equal')\n",
            "        ax.grid(True, linestyle='--', alpha=0.3)\n",
            "        \n",
            "        # Plot Pose (Upper Body)\n",
            "        valid_pose = pose_xy[pose_xy.sum(axis=1) != 0]\n",
            "        if len(valid_pose) > 0:\n",
            "            ax.scatter(valid_pose[:, 0], valid_pose[:, 1], c='blue', s=25, label='Pose')\n",
            "            \n",
            "        # Plot Left Hand\n",
            "        valid_lh = lh_xy[lh_xy.sum(axis=1) != 0]\n",
            "        if len(valid_lh) > 0:\n",
            "            ax.scatter(valid_lh[:, 0], valid_lh[:, 1], c='green', s=35, label='Left Hand')\n",
            "            \n",
            "        # Plot Right Hand\n",
            "        valid_rh = rh_xy[rh_xy.sum(axis=1) != 0]\n",
            "        if len(valid_rh) > 0:\n",
            "            ax.scatter(valid_rh[:, 0], valid_rh[:, 1], c='red', s=35, label='Right Hand')\n",
            "            \n",
            "        if idx == 0:\n",
            "            ax.legend(loc='lower right', fontsize=8)\n",
            "            \n",
            "    plt.tight_layout()\n",
            "    plt.show()\n",
            "\n",
            "sample_npy = glob.glob(os.path.join(CONFIG[\"LOCAL_OUTPUT_DIR\"], '**', '*.npy'), recursive=True)\n",
            "if sample_npy:\n",
            "    print(f\"Displaying skeleton strip for: {sample_npy[0]}\")\n",
            "    plot_extracted_skeleton(sample_npy[0])\n",
            "else:\n",
            "    print(\"ℹ️ Run Cell 6 first to visualize extracted skeletons.\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ── Cell 9: Package Dataset & Backup Directly to Google Drive ────────────────\n",
            "zip_base_name = \"/content/\" + CONFIG[\"OUTPUT_ZIP_NAME\"].replace('.zip', '')\n",
            "dataset_dir = CONFIG[\"LOCAL_OUTPUT_DIR\"]\n",
            "\n",
            "if os.path.exists(dataset_dir) and len(os.listdir(dataset_dir)) > 0:\n",
            "    print(f\"📦 Creating ZIP archive from '{dataset_dir}'...\")\n",
            "    shutil.make_archive(zip_base_name, 'zip', dataset_dir)\n",
            "    local_zip = zip_base_name + \".zip\"\n",
            "    zip_mb = os.path.getsize(local_zip) / (1024 * 1024)\n",
            "    \n",
            "    # Copy ZIP to Google Drive\n",
            "    gdrive_zip_dest = os.path.join(\"/content/drive/MyDrive\", CONFIG[\"OUTPUT_ZIP_NAME\"])\n",
            "    print(f\"💾 Backing up ZIP to Google Drive: {gdrive_zip_dest}...\")\n",
            "    shutil.copy2(local_zip, gdrive_zip_dest)\n",
            "    \n",
            "    print(\"\\n\" + \"=\" * 60)\n",
            "    print(\"🎉 DATASET PACKAGING & GDRIVE BACKUP COMPLETE!\")\n",
            "    print(f\"📁 Local Colab Zip:  {local_zip} ({zip_mb:.2f} MB)\")\n",
            "    print(f\"☁️ Google Drive Zip: {gdrive_zip_dest}\")\n",
            "    print(\"=\" * 60)\n",
            "    print(\"\\n🚀 You can now train directly or upload this ZIP to Kaggle for Few-Shot fine-tuning!\")\n",
            "else:\n",
            "    print(\"ℹ️ Process video files in Cell 6 before creating the backup ZIP.\")"
        ]
    }
]

notebook = {
    "cells": cells,
    "metadata": {
        "accelerator": "GPU",
        "colab": {
            "name": "keypoints.ipynb",
            "provenance": []
        },
        "language_info": {
            "name": "python",
            "version": "3.10"
        },
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

out_path = os.path.join(r"d:\Beta\A_PSL", "keypoints.ipynb")
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2)

print(f"Generated clean manual-path Colab {out_path} with {len(cells)} cells.")
