import json

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# SIMPACT 2026: Foundation Model Fine-Tuning\n",
                "This notebook downloads your How2Sign (H2S) Foundation Model directly from Weights & Biases (wandb), runs a pipeline test, and fine-tunes the network on your new medical phrases."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "# --- 1. DOWNLOAD MODEL FROM WEIGHTS & BIASES ---\n",
                "import wandb\n",
                "import os\n",
                "\n",
                "# TODO: Adjust this path to your exact wandb username/project/artifact\n",
                "WANDB_ARTIFACT_PATH = \"your_username/your_project/h2s_model:latest\"\n",
                "\n",
                "print(f\"Connecting to wandb to download foundation model: {WANDB_ARTIFACT_PATH}\")\n",
                "try:\n",
                "    api = wandb.Api()\n",
                "    artifact = api.artifact(WANDB_ARTIFACT_PATH)\n",
                "    download_dir = artifact.download(root=\"./h2s_foundation_model\")\n",
                "    \n",
                "    # Find the .pt file in the downloaded folder\n",
                "    pt_files = [f for f in os.listdir(download_dir) if f.endswith('.pt')]\n",
                "    if pt_files:\n",
                "        FOUNDATION_MODEL_PATH = os.path.join(download_dir, pt_files[0])\n",
                "        print(f\"\\nSuccess! Downloaded Foundation Model: {FOUNDATION_MODEL_PATH}\")\n",
                "    else:\n",
                "        print(\"\\nError: Downloaded artifact, but no .pt file found inside.\")\n",
                "        FOUNDATION_MODEL_PATH = \"model_not_found.pt\"\n",
                "except Exception as e:\n",
                "    print(f\"\\nFailed to download from wandb. Error: {e}\")\n",
                "    print(\"Make sure you are logged in (run 'wandb login' in terminal) and the artifact path is correct.\")\n",
                "    FOUNDATION_MODEL_PATH = \"sana_psl_complete_55mb.pt\" # Fallback"
            ],
            "outputs": []
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "import numpy as np\n",
                "import torch\n",
                "import torch.nn as nn\n",
                "import math\n",
                "from torch.utils.data import Dataset, DataLoader, Subset\n",
                "from sklearn.model_selection import train_test_split\n",
                "import time\n",
                "import matplotlib.pyplot as plt\n",
                "from transformers import AutoModelForSeq2SeqLM, AutoTokenizer\n",
                "\n",
                "# --- 2. CONFIGURATION ---\n",
                "CONFIG = {\n",
                "    \"DATASET_DIR\":      \"E:/sign-language/dataset\",\n",
                "    \"PRETRAINED_MODEL\": FOUNDATION_MODEL_PATH,  # Dynamically points to downloaded W&B file\n",
                "    \"MT5_MODEL_NAME\":   \"google/mt5-small\",\n",
                "    \"D_MODEL\":          512,\n",
                "    \"NUM_HEADS\":        8,\n",
                "    \"NUM_ENCODER_LAYERS\": 2,\n",
                "    \"DIM_FEEDFORWARD\":  1024,\n",
                "    \"DROPOUT\":          0.108,\n",
                "    \"MAX_SEQ_LEN\":      100,\n",
                "    \"MAX_TARGET_LEN\":   32,\n",
                "    \"INPUT_DIM\":        208,\n",
                "    \"EPOCHS\":           60,     # High epochs for 40-video overfitting test\n",
                "    \"BATCH_SIZE\":       4,\n",
                "    \"LEARNING_RATE\":    5e-5,\n",
                "}\n",
                "\n",
                "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
                "print(f\"Using device: {device}\")"
            ],
            "outputs": []
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Defining the Architecture (Exactly as Trained on H2S)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "# --- 3. SANA ARCHITECTURE ---\n",
                "class SinusoidalPositionalEncoding(nn.Module):\n",
                "    def __init__(self, d_model, max_len=500):\n",
                "        super().__init__()\n",
                "        pe = torch.zeros(max_len, d_model)\n",
                "        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)\n",
                "        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))\n",
                "        pe[:, 0::2] = torch.sin(position * div_term)\n",
                "        pe[:, 1::2] = torch.cos(position * div_term)\n",
                "        self.register_buffer('pe', pe.unsqueeze(0))\n",
                "\n",
                "    def forward(self, x):\n",
                "        x = x + self.pe[:, :x.size(1), :]\n",
                "        return x\n",
                "\n",
                "class TemporalGestureTokenizer(nn.Module):\n",
                "    def __init__(self, input_dim=208, d_model=512):\n",
                "        super().__init__()\n",
                "        self.conv1 = nn.Conv1d(input_dim, d_model // 2, kernel_size=5, stride=2, padding=2)\n",
                "        self.norm1 = nn.BatchNorm1d(d_model // 2)\n",
                "        self.gelu  = nn.GELU()\n",
                "        self.conv2 = nn.Conv1d(d_model // 2, d_model, kernel_size=5, stride=2, padding=2)\n",
                "        self.norm2 = nn.BatchNorm1d(d_model)\n",
                "        \n",
                "    def forward(self, x):\n",
                "        x = x.transpose(1, 2)\n",
                "        x = self.conv1(x)\n",
                "        x = self.norm1(x)\n",
                "        x = self.gelu(x)\n",
                "        x = self.conv2(x)\n",
                "        x = self.norm2(x)\n",
                "        x = self.gelu(x)\n",
                "        x = x.transpose(1, 2)\n",
                "        return x\n",
                "\n",
                "class UpgradedSpatialTemporalEncoder(nn.Module):\n",
                "    def __init__(self, input_dim, d_model, num_heads, num_layers, ffn_dim, dropout, max_len):\n",
                "        super().__init__()\n",
                "        self.tokenizer = TemporalGestureTokenizer(input_dim, d_model)\n",
                "        self.pos_encoder = SinusoidalPositionalEncoding(d_model, max_len=100)\n",
                "        encoder_layer = nn.TransformerEncoderLayer(\n",
                "            d_model=d_model, nhead=num_heads, dim_feedforward=ffn_dim,\n",
                "            dropout=dropout, activation=\"gelu\", batch_first=True\n",
                "        )\n",
                "        self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)\n",
                "        self.norm = nn.LayerNorm(d_model)\n",
                "        \n",
                "    def forward(self, src):\n",
                "        x = self.tokenizer(src)\n",
                "        x = self.pos_encoder(x)\n",
                "        x = self.transformer_encoder(x)\n",
                "        x = self.norm(x)\n",
                "        return x\n",
                "\n",
                "class SANA_PSL_Translator(nn.Module):\n",
                "    def __init__(self, config):\n",
                "        super().__init__()\n",
                "        self.visual_encoder = UpgradedSpatialTemporalEncoder(\n",
                "            input_dim=config[\"INPUT_DIM\"],\n",
                "            d_model=config[\"D_MODEL\"],\n",
                "            num_heads=config[\"NUM_HEADS\"],\n",
                "            num_layers=config[\"NUM_ENCODER_LAYERS\"],\n",
                "            ffn_dim=config[\"DIM_FEEDFORWARD\"],\n",
                "            dropout=config[\"DROPOUT\"],\n",
                "            max_len=config[\"MAX_SEQ_LEN\"]\n",
                "        )\n",
                "        self.mt5 = AutoModelForSeq2SeqLM.from_pretrained(config[\"MT5_MODEL_NAME\"])\n",
                "        \n",
                "    def forward(self, src, labels=None):\n",
                "        encoder_outputs = self.visual_encoder(src)\n",
                "        if labels is not None:\n",
                "            outputs = self.mt5(encoder_outputs= (encoder_outputs,), labels=labels)\n",
                "        else:\n",
                "            outputs = self.mt5(encoder_outputs= (encoder_outputs,))\n",
                "        return outputs\n"
            ],
            "outputs": []
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "# --- 4. LOADING THE H2S FOUNDATION MODEL & TOKENIZER ---\n",
                "tokenizer = AutoTokenizer.from_pretrained(CONFIG[\"MT5_MODEL_NAME\"])\n",
                "model = SANA_PSL_Translator(CONFIG)\n",
                "\n",
                "if os.path.exists(CONFIG[\"PRETRAINED_MODEL\"]):\n",
                "    print(f\"Loading existing Foundation weights from {CONFIG['PRETRAINED_MODEL']}...\")\n",
                "    # Handle state dict structure depending on how you saved it in wandb\n",
                "    checkpoint = torch.load(CONFIG[\"PRETRAINED_MODEL\"], map_location=device)\n",
                "    if \"model_state_dict\" in checkpoint:\n",
                "        # If you saved only the visual encoder previously, this handles it\n",
                "        try:\n",
                "            model.load_state_dict(checkpoint[\"model_state_dict\"])\n",
                "        except:\n",
                "            model.visual_encoder.load_state_dict(checkpoint[\"model_state_dict\"])\n",
                "    else:\n",
                "        model.load_state_dict(checkpoint)\n",
                "    print(\"Successfully loaded Foundation Model!\")\n",
                "else:\n",
                "    print(\"WARNING: Pretrained model not found! Training from scratch.\")\n",
                "model = model.to(device)\n"
            ],
            "outputs": []
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### The Medical Dataset Loader"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "# --- 5. DATASET PREPARATION ---\n",
                "class MedicalDataset(Dataset):\n",
                "    def __init__(self, dataset_dir, tokenizer, config):\n",
                "        self.samples = []\n",
                "        self.tokenizer = tokenizer\n",
                "        self.config = config\n",
                "        \n",
                "        if not os.path.exists(dataset_dir):\n",
                "            print(f\"Dataset dir {dataset_dir} not found.\")\n",
                "            return\n",
                "            \n",
                "        for folder in os.listdir(dataset_dir):\n",
                "            folder_path = os.path.join(dataset_dir, folder)\n",
                "            if os.path.isdir(folder_path):\n",
                "                label = folder.replace(\"_\", \" \")\n",
                "                for file in os.listdir(folder_path):\n",
                "                    if file.endswith(\".npy\"):\n",
                "                        self.samples.append((os.path.join(folder_path, file), label))\n",
                "        print(f\"Found {len(self.samples)} samples across {len(os.listdir(dataset_dir))} classes.\")\n",
                "        \n",
                "    def __len__(self):\n",
                "        return len(self.samples)\n",
                "        \n",
                "    def __getitem__(self, idx):\n",
                "        npy_path, label = self.samples[idx]\n",
                "        data = np.load(npy_path)\n",
                "        \n",
                "        # Sequence Padding/Truncating\n",
                "        T = data.shape[0]\n",
                "        if T > self.config[\"MAX_SEQ_LEN\"]:\n",
                "            data = data[:self.config[\"MAX_SEQ_LEN\"]]\n",
                "        elif T < self.config[\"MAX_SEQ_LEN\"]:\n",
                "            padding = np.zeros((self.config[\"MAX_SEQ_LEN\"] - T, self.config[\"INPUT_DIM\"]))\n",
                "            data = np.vstack([data, padding])\n",
                "            \n",
                "        data_tensor = torch.tensor(data, dtype=torch.float32)\n",
                "        \n",
                "        tokenized = self.tokenizer(\n",
                "            label,\n",
                "            padding=\"max_length\",\n",
                "            truncation=True,\n",
                "            max_length=self.config[\"MAX_TARGET_LEN\"],\n",
                "            return_tensors=\"pt\"\n",
                "        )\n",
                "        label_tensor = tokenized.input_ids.squeeze(0)\n",
                "        label_tensor[label_tensor == self.tokenizer.pad_token_id] = -100\n",
                "        \n",
                "        return data_tensor, label_tensor, label\n",
                "\n",
                "med_dataset = MedicalDataset(CONFIG[\"DATASET_DIR\"], tokenizer, CONFIG)\n",
                "\n",
                "# Train-Test Split (80/20)\n",
                "indices = list(range(len(med_dataset)))\n",
                "if len(indices) > 1:\n",
                "    train_indices, val_indices = train_test_split(indices, test_size=0.2, random_state=42)\n",
                "else:\n",
                "    train_indices, val_indices = indices, indices\n",
                "\n",
                "train_dataset = Subset(med_dataset, train_indices)\n",
                "val_dataset = Subset(med_dataset, val_indices)\n",
                "\n",
                "train_loader = DataLoader(train_dataset, batch_size=CONFIG[\"BATCH_SIZE\"], shuffle=True)\n",
                "val_loader = DataLoader(val_dataset, batch_size=CONFIG[\"BATCH_SIZE\"], shuffle=False)\n",
                "print(f\"Split dataset: {len(train_dataset)} train, {len(val_dataset)} validation\")"
            ],
            "outputs": []
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Step 1: INFERENCE TEST (Verify Pipeline works on H2S Weights)\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "if len(train_dataset) > 0:\n",
                "    test_data, _, true_label = train_dataset[0]\n",
                "    test_data = test_data.unsqueeze(0).to(device)\n",
                "    \n",
                "    model.eval()\n",
                "    with torch.no_grad():\n",
                "        encoder_outputs = model.visual_encoder(test_data)\n",
                "        outputs = model.mt5.generate(\n",
                "            encoder_outputs=(encoder_outputs,),\n",
                "            max_length=CONFIG[\"MAX_TARGET_LEN\"]\n",
                "        )\n",
                "        pred_text = tokenizer.decode(outputs[0], skip_special_tokens=True)\n",
                "        \n",
                "    print(f\"\\n--- PIPELINE INFERENCE TEST ---\")\n",
                "    print(f\"Ground Truth (What you signed): {true_label}\")\n",
                "    print(f\"H2S Foundation Model Raw Prediction: {pred_text}\")\n",
                "    print(f\"Pipeline status: SUCCESS! (Output text is expected to be wrong before fine-tuning)\")"
            ],
            "outputs": []
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Step 2: TRANSFER LEARNING (Fine-Tuning on Medical Videos)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "# Freeze mT5, unfreeze cross-attention to train fast\n",
                "for param in model.mt5.parameters():\n",
                "    param.requires_grad = False\n",
                "for block in model.mt5.decoder.block:\n",
                "    for param in block.layer[1].parameters():\n",
                "        param.requires_grad = True\n",
                "        \n",
                "optimizer = torch.optim.AdamW(filter(lambda p: p.requires_grad, model.parameters()), lr=CONFIG[\"LEARNING_RATE\"])\n",
                "\n",
                "print(\"Starting Fine-Tuning on the Medical Dataset...\")\n",
                "train_losses, val_losses, val_accuracies, val_confidences, val_latencies = [], [], [], [], []\n",
                "for epoch in range(CONFIG[\"EPOCHS\"]):\n",
                "    model.train()\n",
                "    total_train_loss = 0\n",
                "    for batch_data, batch_labels, _ in train_loader:\n",
                "        batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)\n",
                "        optimizer.zero_grad()\n",
                "        outputs = model(src=batch_data, labels=batch_labels)\n",
                "        loss = outputs.loss\n",
                "        loss.backward()\n",
                "        optimizer.step()\n",
                "        total_train_loss += loss.item()\n",
                "    avg_train_loss = total_train_loss / max(len(train_loader), 1)\n",
                "    train_losses.append(avg_train_loss)\n",
                "    \n",
                "    model.eval()\n",
                "    total_val_loss, correct_preds, total_preds = 0, 0, 0\n",
                "    epoch_confidences, epoch_latencies = [], []\n",
                "    with torch.no_grad():\n",
                "        for batch_data, batch_labels, batch_text_labels in val_loader:\n",
                "            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)\n",
                "            outputs = model(src=batch_data, labels=batch_labels)\n",
                "            total_val_loss += outputs.loss.item()\n",
                "            \n",
                "            start_time = time.time()\n",
                "            encoder_outputs = model.visual_encoder(batch_data)\n",
                "            gen_outputs = model.mt5.generate(encoder_outputs=(encoder_outputs,), max_length=CONFIG[\"MAX_TARGET_LEN\"], return_dict_in_generate=True, output_scores=True)\n",
                "            epoch_latencies.append((time.time() - start_time) / batch_data.size(0))\n",
                "            \n",
                "            for i in range(len(gen_outputs.sequences)):\n",
                "                pred_text = tokenizer.decode(gen_outputs.sequences[i], skip_special_tokens=True).strip().lower()\n",
                "                true_text = batch_text_labels[i].strip().lower()\n",
                "                if pred_text == true_text: correct_preds += 1\n",
                "                total_preds += 1\n",
                "                if len(gen_outputs.scores) > 0:\n",
                "                    probs = torch.nn.functional.softmax(gen_outputs.scores[0][i], dim=-1)\n",
                "                    epoch_confidences.append(torch.max(probs).item())\n",
                "    \n",
                "    avg_val_loss = total_val_loss / max(len(val_loader), 1)\n",
                "    val_losses.append(avg_val_loss)\n",
                "    accuracy = (correct_preds / total_preds * 100) if total_preds > 0 else 0\n",
                "    val_accuracies.append(accuracy)\n",
                "    avg_conf = sum(epoch_confidences) / len(epoch_confidences) if epoch_confidences else 0\n",
                "    val_confidences.append(avg_conf)\n",
                "    avg_lat = sum(epoch_latencies) / len(epoch_latencies) if epoch_latencies else 0\n",
                "    val_latencies.append(avg_lat * 1000)\n",
                "    \n",
                "    print(f\"Epoch [{epoch+1}/{CONFIG['EPOCHS']}] | Train Loss: {avg_train_loss:.4f} | Val Loss: {avg_val_loss:.4f} | Val Acc: {accuracy:.1f}% | Conf: {avg_conf*100:.1f}% | Latency: {avg_lat*1000:.1f}ms\")\n",
                "torch.save(model.state_dict(), \"sana_psl_medical_finetuned.pt\")\n",
                "print(\"Fine-tuning complete! Saved weights as sana_psl_medical_finetuned.pt\")"
            ],
            "outputs": []
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Step 3: Visualization & Metrics\n",
                "Plot the training curves, accuracy, confidence, and latency."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "import matplotlib.pyplot as plt\n",
                "\n",
                "fig, axs = plt.subplots(2, 2, figsize=(15, 10))\n",
                "\n",
                "# 1. Loss\n",
                "axs[0, 0].plot(train_losses, label='Train Loss', color='blue')\n",
                "axs[0, 0].plot(val_losses, label='Val Loss', color='red')\n",
                "axs[0, 0].set_title('Training & Validation Loss')\n",
                "axs[0, 0].set_xlabel('Epochs')\n",
                "axs[0, 0].set_ylabel('Loss')\n",
                "axs[0, 0].legend()\n",
                "\n",
                "# 2. Accuracy\n",
                "axs[0, 1].plot(val_accuracies, label='Validation Accuracy', color='green')\n",
                "axs[0, 1].set_title('Exact Match Accuracy')\n",
                "axs[0, 1].set_xlabel('Epochs')\n",
                "axs[0, 1].set_ylabel('Accuracy (%)')\n",
                "axs[0, 1].legend()\n",
                "\n",
                "# 3. Confidence\n",
                "axs[1, 0].plot([c * 100 for c in val_confidences], label='Val Confidence', color='purple')\n",
                "axs[1, 0].set_title('Average Top-1 Confidence')\n",
                "axs[1, 0].set_xlabel('Epochs')\n",
                "axs[1, 0].set_ylabel('Confidence (%)')\n",
                "axs[1, 0].legend()\n",
                "\n",
                "# 4. Latency\n",
                "axs[1, 1].plot(val_latencies, label='Inference Latency', color='orange')\n",
                "axs[1, 1].set_title('Per-Sample Generation Latency')\n",
                "axs[1, 1].set_xlabel('Epochs')\n",
                "axs[1, 1].set_ylabel('Latency (ms)')\n",
                "axs[1, 1].legend()\n",
                "\n",
                "plt.tight_layout()\n",
                "plt.show()" 
            ],
            "outputs": []
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

with open("test_model.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=4)
print("Successfully generated updated test_model.ipynb with W&B integration")
